import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { TaskCard } from './TaskCard';
import type { Task } from './TaskCard.types';

const mockTask: Task = {
  id: 'task-123',
  title: 'Implement TaskCard Component',
  description: 'Build a co-located React component for daily task management.',
  status: 'TODO',
  priority: 'HIGH',
  dueDate: '2026-08-01T00:00:00.000Z',
};

describe('<TaskCard />', () => {
  it('renders task details correctly', () => {
    render(<TaskCard task={mockTask} onStatusChange={vi.fn()} />);

    expect(screen.getByText('Implement TaskCard Component')).toBeInTheDocument();
    expect(
      screen.getByText('Build a co-located React component for daily task management.')
    ).toBeInTheDocument();
    expect(screen.getByText('High')).toBeInTheDocument();
    expect(screen.getByText('Aug 1, 2026')).toBeInTheDocument();
  });

  it('triggers onStatusChange callback when status dropdown option changes', async () => {
    const handleStatusChange = vi.fn();
    const user = userEvent.setup();

    render(<TaskCard task={mockTask} onStatusChange={handleStatusChange} />);

    // Accessible name generated by t('tasks.actions.changeStatus', { title })
    const statusSelect = screen.getByRole('combobox', {
      name: 'Change status for Implement TaskCard Component',
    });

    await user.selectOptions(statusSelect, 'COMPLETED');

    expect(handleStatusChange).toHaveBeenCalledTimes(1);
    expect(handleStatusChange).toHaveBeenCalledWith('task-123', 'COMPLETED');
  });

  it('triggers onDelete when delete icon button is clicked', async () => {
    const handleDelete = vi.fn();
    const user = userEvent.setup();

    render(<TaskCard task={mockTask} onStatusChange={vi.fn()} onDelete={handleDelete} />);

    // Accessible name generated by t('tasks.actions.delete', { title })
    const deleteBtn = screen.getByRole('button', {
      name: 'Delete task Implement TaskCard Component',
    });

    await user.click(deleteBtn);

    expect(handleDelete).toHaveBeenCalledTimes(1);
    expect(handleDelete).toHaveBeenCalledWith('task-123');
  });
});